import {
  Geist,
  Geist_Mono,
  Gloock,
  Dosis,
  Comic_Neue,
  Mountains_of_Christmas,
} from "next/font/google";

import "./globals.css";
import Nav from "./Components/Nav/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const gloock = Gloock({
  variable: "--font-gloock",
  subsets: ["latin"],
  weight: ["400"],
});

const comicNeue = Comic_Neue({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const mountainsOfChristmas = Mountains_of_Christmas({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gloock.variable} ${dosis.variable} ${comicNeue.variable} ${mountainsOfChristmas.variable}`}
      >
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  );
}
