# Generated by Django 5.2.4 on 2025-07-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
