# Generated by Django 5.2.4 on 2025-07-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generatedimage_author_generatedimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.JSONField(default=list, help_text='Texto gerado pelo GPT em formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
